apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    app: wakate-monorepo-app
spec:
  selector:
    app: wakate-monorepo-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer